plugins {
    id "com.android.application"
}

android {
    namespace "dev.mali.lab"
    compileSdk 34

    defaultConfig {
        applicationId "dev.mali.lab"
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName "3.0-mali"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(":graphics")
}
